### ISSUE TITLE
minimum-stability issues

### ISSUE THREAD

**Issue by hettiger** [hettiger/larawire#1]
composer require not working as described in the readme

**Comment by hettiger** [comment]
![bildschirmfoto 2014-12-02 um 22 21 20](https://cloud.githubusercontent.com/assets/4583871/5271095/927779e6-7a71-11e4-88d7-32866c704625.png)

**Comment by hettiger** [comment]
Still experiencing problems ...

**Comment by hettiger** [comment]
Fixed.

**Comment by phpexpert00784** [comment]
I am getting same issues in above image with below code.

{
    "name": "ephyre/voxilo-cakephp-teams-plugin",
    "minimum-stability" : "dev",
    "prefer-stable" : true,
	"repositories": [
    {
        "type": "vcs",
        "url": "git@bitbucket.org:ephyre/voxilo-cakephp-teams-plugin.git"        
    }
    ]
}

**Comment by hettiger** [comment]
Hello @phpexpert00784 

Is your problem actually even related to this project?

**Comment by phpexpert00784** [comment]
Its a another project. But i am very thankfull if you help me out

**Comment by hettiger** [comment]
@phpexpert00784 You need to do something like described in https://github.com/hettiger/larawire#installation 

In your case since you're using type vcs you may use something like

```
            ...
            "dist": {
                "url": "git@bitbucket.org:ephyre/voxilo-cakephp-teams-plugin.git",
                "type": "vcs"
            }
            ...
```

Just make sure you define a package in the repositories section first and then add it to the require section. That should do the trick. If that doesn't help you, have a look at the [composer documentation](https://getcomposer.org/doc/04-schema.md#repositories). You should be up and running in no time. :-)
